Update overlay of sgx5150,pw2050

diff --git a/sources/meta-lantronix/recipes-bsp/images/files/pw2050-overlay/etc/sysconfig/network-scripts/bcmSoftApCtrl b/sources/meta-lantronix/recipes-bsp/images/files/pw2050-overlay/etc/sysconfig/network-scripts/bcmSoftApCtrl
--- a/sources/meta-lantronix/recipes-bsp/images/files/pw2050-overlay/etc/sysconfig/network-scripts/bcmSoftApCtrl
+++ b/sources/meta-lantronix/recipes-bsp/images/files/pw2050-overlay/etc/sysconfig/network-scripts/bcmSoftApCtrl
@@ -106,6 +106,16 @@ if [ "$1" == "start" ]; then
         exit 1
     fi
 
+    if [ "$SSID_BROADCAST" == "no" ]; then
+        #closed is 0 (open) by default
+        wl -i wl0.1 closed 1
+        rc=$?
+        if [ $rc != 0 ]; then
+            logger -p "user.err" "closed failed with ${rc}"
+            exit 1
+        fi
+    fi
+
     wl -i wl0.1 wsec "$ENCRYPTION"
     rc=$?
     if [ $rc != 0 ]; then
